FROM node:18.20.1-bullseye-slim

ENV AWSCLI_VERSION=2.10.1

RUN apt update && apt install -y --no-install-recommends \
    curl ca-certificates bash \
    postgresql-client \
    # Needed to install awscli
    unzip \
    git \
    patch \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp && git clone -b deepnote-v2.1 --single-branch --depth 1 https://github.com/deepnote/aws-cli && \
    cd /tmp/aws-cli && \
    pip install .

